In [16]:
import numpy as np
import pandas as pd
from numpy.linalg import norm, eig
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [17]:
df = pd.read_csv(r"/content/student_performance.csv")

1. Represent each student's scores as vector

In [18]:

student1 = df.loc[0, ['Maths','Science','English','Computer','Statistics']].values
student2 = df.loc[1, ['Maths','Science','English','Computer','Statistics']].values

print("Student 1 Vector :", student1)
print("Student 2 Vector :", student2)

Student 1 Vector : [np.int64(54) np.int64(50) np.int64(94) np.int64(80) np.int64(56)]
Student 2 Vector : [np.int64(65) np.int64(82) np.int64(69) np.int64(75) np.int64(51)]

2. Norm-1

In [19]:

norm1 = np.linalg.norm(student1, ord=1)

print("Norm-1 :", norm1)

Norm-1 : 334

3. Norm-2

In [20]:

norm2 = np.linalg.norm(student1)

print("Norm-2 :", norm2)

Norm-2 : 154.2335890783846

4. Dot Product

In [21]:

dot_product = np.dot(student1, student2)

print("Dot Product :", dot_product)

Dot Product : 22952

5. Angle Between Two Vectors

In [22]:

cos_theta = np.dot(student1, student2) / (np.linalg.norm(student1) * np.linalg.norm(student2))

angle = np.degrees(np.arccos(cos_theta))

print("Angle Between Vectors :", angle)

Angle Between Vectors : 15.873340643266367

6. Cross Product

In [23]:
v1 = student1[:3].astype(int)
v2 = student2[:3].astype(int)

cross_product = np.cross(v1, v2)

print("Cross Product :", cross_product)

Cross Product : [-4258  2384  1178]

7. Projection of One Vector onto Another

In [24]:

projection = (np.dot(student1, student2) / np.dot(student2, student2)) * student2

print("Projection :", projection)

Projection : [np.float64(62.3278743315508) np.float64(78.62901069518716)
 np.float64(66.163435828877) np.float64(71.91677807486631)
 np.float64(48.903409090909086)]

PART B : MATRIX OPERATIONS

In [25]:
A = df[['Maths','Science','English','Computer','Statistics']].head(5).values

print(A)

[[ 54  50  94  80  56]
 [ 65  82  69  75  51]
 [ 54  60 100  85  85]
 [ 66  96  81  91  64]
 [ 88  70  96  98  59]]

9. Matrix Addition

In [26]:

B = np.array([
    [1,2,3,4,5],
    [5,4,3,2,1],
    [1,1,1,1,1],
    [2,2,2,2,2],
    [3,3,3,3,3]
])

addition = A + B

print(addition)

[[ 55  52  97  84  61]
 [ 70  86  72  77  52]
 [ 55  61 101  86  86]
 [ 68  98  83  93  66]
 [ 91  73  99 101  62]]

10. Matrix Multiplication

In [27]:

multiplication = np.matmul(A, B)

print(multiplication)

[[ 726  730  734  738  742]
 [ 847  830  813  796  779]
 [ 879  873  867  861  855]
 [1001  971  941  911  881]
 [ 907  925  943  961  979]]


11. Transpose

In [28]:

transpose = A.T


print(transpose)

[[ 54  65  54  66  88]
 [ 50  82  60  96  70]
 [ 94  69 100  81  96]
 [ 80  75  85  91  98]
 [ 56  51  85  64  59]]

12. Determinant

In [29]:

determinant = np.linalg.det(A)

print("Determinant :", determinant)

Determinant : 16055130.000000069

13. Inverse

In [30]:

inverse = np.linalg.inv(A)

print(inverse)

[[-0.02746038  0.05741903  0.01242593 -0.05869713  0.02220038]
 [ 0.01860807  0.05659313 -0.00984919 -0.01558007 -0.03549146]
 [ 0.06652715  0.09544688 -0.01216695 -0.07248113 -0.04949708]
 [-0.0233128  -0.18059025 -0.01843834  0.13677248  0.05643118]
 [-0.05064412 -0.00812625  0.04357536 -0.00321293  0.01274969]]

PART C : LINEAR TRANSFORMATIONS

14. Linear Transformation

In [31]:

transformation_matrix = np.array([
    [1,0],
    [0,2]
])

points = np.array([
    [2,3],
    [4,5]
])

transformed_points = np.dot(points, transformation_matrix)

print(transformed_points)

[[ 2  6]
 [ 4 10]]

PART D : EIGENVALUES & DECOMPOSITION

15. Covariance Matrix

In [32]:

cov_matrix = np.cov(A.T)

print(cov_matrix)

[[ 192.8    88.2    -5.25   89.6   -64.  ]
 [  88.2   326.8  -162.5    32.4   -49.5 ]
 [  -5.25 -162.5   163.5    55.5   102.75]
 [  89.6    32.4    55.5    81.7    27.25]
 [ -64.    -49.5   102.75   27.25  173.5 ]]

16. Eigenvalues & Eigenvectors

In [33]:

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues :")
print(eigenvalues)

print("\nEigenvectors :")
print(eigenvectors)

Eigenvalues :
[4.90347137e+02 2.50092976e+02 1.80641589e+02 1.72182981e+01
 2.88127339e-15]

Eigenvectors :
[[ 0.31477676  0.6805143   0.35994305 -0.5384739  -0.13528764]
 [ 0.75061815  0.04922015 -0.52063448  0.23541579 -0.32812942]
 [-0.47530903  0.44399944 -0.05670115  0.40601869 -0.63943697]
 [ 0.04188004  0.54871323 -0.08761613  0.49115962  0.66951138]
 [-0.33138403  0.19040996 -0.76713046 -0.49853417  0.13001238]]

17. LU Decomposition

In [34]:

from scipy.linalg import lu

P, L, U = lu(A)

print("P Matrix :")
print(P)

P Matrix :
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

18. Singular Value Decomposition (SVD)

In [35]:

U, S, VT = np.linalg.svd(A)

print("U Matrix :")
print(U)

print("\nSingular Values :")
print(S)

print("\nVT Matrix :")
print(VT)

U Matrix :
[[-0.40343951  0.4368569  -0.21181592  0.75470395 -0.17874165]
 [-0.40455725 -0.49004884  0.08384944 -0.08961132 -0.76231532]
 [-0.45821086  0.58575266  0.49170783 -0.45219126 -0.02613617]
 [-0.47208856 -0.47295076  0.4000762   0.26799163  0.56707099]
 [-0.49065793 -0.04711248 -0.73909792 -0.38222417  0.25431117]]

Singular Values :
[378.55218793  44.19216369  27.93913634   9.87977957   3.47682289]

VT Matrix :
[[-0.38874715 -0.4239967  -0.52040693 -0.50880544 -0.37335787]
 [-0.27138084 -0.72178287  0.52033286  0.00742944  0.36685207]
 [-0.64680634  0.44589027 -0.12532706 -0.17488234  0.5801144 ]
 [-0.5503493   0.22541985  0.46090764  0.21746231 -0.62175222]
 [-0.23234735 -0.22276457 -0.47988291  0.81436364  0.0539899 ]]

PART E : DIMENSIONALITY REDUCTION

19. PCA

In [36]:

from sklearn.decomposition import PCA

X = df[['Maths','Science','English','Computer','Statistics']]

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X)

print(pca_result)

[[-40.11044725  -0.43510536]
 [-18.67613885 -26.06382432]
 [-21.3700827   21.32251691]
 [ -8.27258815 -17.03077953]
 [-12.91639878 -12.1890303 ]
 [ 10.14362805 -18.79112941]
 [ 21.80300817   6.44007493]
 [  6.65232862   5.90022491]
 [ -1.96479618  21.97880367]
 [-10.09045388 -23.79710945]
 [ -0.60546587  -6.87220688]
 [ -1.5077291    7.78254324]
 [-15.5643685   24.65115552]
 [-20.42558295  28.27501924]
 [ -9.27011949  13.03095197]
 [ -2.58061903 -29.27149683]
 [ 10.55419966  13.49911776]
 [ 12.17332667  -1.9099339 ]
 [ 20.1138143   -6.38552734]
 [ 10.22944034   1.17312211]
 [ 13.9882385    5.41091305]
 [ 15.96536822  -5.06585118]
 [-24.26194165 -14.11989213]
 [-21.25601016 -12.55030382]
 [ 10.75449944  10.68035797]
 [ 31.38466011  -2.0496118 ]
 [ 26.77357581 -12.72288364]
 [  0.32703698  20.15991241]
 [ 21.13501666   7.65468729]
 [ -3.12539898   1.2952849 ]]

20. PCA DataFrame

In [37]:

pca_df = pd.DataFrame(pca_result, columns=['PC1','PC2'])

pca_df.head()

         PC1        PC2
0 -40.110447  -0.435105
1 -18.676139 -26.063824
2 -21.370083  21.322517
3  -8.272588 -17.030780
4 -12.916399 -12.189030

21. LDA

In [38]:

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X = df[['Maths','Science','English','Computer','Statistics']]

y = df['Performance_Category']

lda = LinearDiscriminantAnalysis(n_components=1)

lda_result = lda.fit_transform(X, y)

print(lda_result)

[[ 2.6110955 ]
 [ 2.74700891]
 [-0.57630715]
 [-0.99898253]
 [-1.53616025]
 [-0.03131897]
 [-0.90123593]
 [-0.31198297]
 [-2.67602842]
 [ 2.70694556]
 [-0.6018956 ]
 [-2.66302892]
 [-1.00078811]
 [ 2.16314153]
 [ 0.18094534]
 [ 2.22773549]
 [ 1.53334125]
 [-0.89339428]
 [-1.39734361]
 [-0.04911396]
 [-2.36274325]
 [-2.07195873]
 [ 4.59680989]
 [ 1.94006522]
 [-2.76968238]
 [-0.95531833]
 [-0.31885824]
 [ 1.74231903]
 [-2.0952376 ]
 [ 1.76197151]]

22. LDA DataFrame

In [39]:

lda_df = pd.DataFrame(lda_result, columns=['LD1'])

lda_df.head()

        LD1
0  2.611095
1  2.747009
2 -0.576307
3 -0.998983
4 -1.536160

FINAL CONCLUSION

In [40]:

print("Project Completed Successfully")

Project Completed Successfully